version: 2

orb:
  postman: postman/newman@0.0.1
  
  
jobs:
  buildapi:
    docker:
      - image: circleci/node
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: NPM Ignore
          command: 'sudo npm i -g npmignore'
      
      - run:
          name: Install Newman
          command: 'sudo npm install -g newman'
          
      - run:
          name: Working Dir
          command: 'ls -la'

 
      - run:
          name: API Testing
          command: 'newman run ./api/ht.json'


  # builde2e:
  #   docker:
  #     - image: circleci/node:10.14-browsers

  #   working_directory: ~/repo

  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "package.json" }}
  #         - v1-dependencies-

  #     - run: yarn install

  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}

  #     - run: yarn e2e

  #     - store_test_results:
  #         path: /tmp/test-results

workflows:
  version: 2
  buildapi_tests:
    jobs:
      - buildapi
  # builde2e_tests:
  #   jobs:
  #   - builde2e