version: 2

orb:
  postman: postman/newman@0.0.1
  
  
jobs:
  buildapi:
    docker:
      - image: circleci/node
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: NPM Ignore
          command: 'sudo npm i -g npmignore'
      
      - run:
          name: Install Newman
          command: 'sudo npm install -g newman'
          
      - run:
          name: Working Dir
          command: 'ls -la'

 
      - run:
          name: API Testing
          command: 'newman run ./api/ht.json'